name: Quick Text Change
description: Request a simple wording change in the web form (labels, buttons, hints).
title: "Text: "
labels: [ui, quick-fix]

body:
  - type: markdown
    attributes:
      value: |
        Use this for simple text changes only (labels, placeholders, button text, hints).
        
        **Not sure if this is the right template?**
        - For bugs or broken features → use **Bug Report**
        - For new features or major changes → use **Feature Request**

  - type: input
    id: where
    attributes:
      label: Where is it on the page?
      description: "Help us find it quickly."
      placeholder: 'Example: "Name for filename" field in the Basic Information section'
    validations:
      required: true

  - type: input
    id: current
    attributes:
      label: What does it currently say?
      description: "Copy the exact text you see."
      placeholder: 'Example: Enter your desired filename'
    validations:
      required: true

  - type: input
    id: desired
    attributes:
      label: What should it say instead?
      placeholder: 'Example: Filename for the Word document (without .docx)'
    validations:
      required: true
  
  - type: textarea
    id: why
    attributes:
      label: Why change it? (optional)
      description: "Help us understand the improvement."
      placeholder: "Example: Current text is confusing because users don't know if they need to add .docx"
    validations:
      required: false

  - type: checkboxes
    id: constraints
    attributes:
      label: Confirm this is a simple text change
      description: "Check all that apply (helps keep the change small and fast)."
      options:
        - label: Wording/text only (no changes to functionality)
        - label: No changes to the Word document output
        - label: No changes outside this specific field/section

  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      description: Screenshot, links, or other context.
    validations:
      required: false
