name: UI Text / Placeholder Change
description: Request a simple wording change in the web form.
title: "UI: "
labels: [ui]

body:
  - type: markdown
    attributes:
      value: |
        Use this when you want to change a label, placeholder, hint text, or button text.

  - type: input
    id: where
    attributes:
      label: Where is it on the page?
      description: "For example: Basic Information section, or near the AI Assist panel."
      placeholder: "Name for filename field (top section)"
    validations:
      required: true

  - type: input
    id: current
    attributes:
      label: What does it currently say?
      description: "Copy the exact text you see (label/placeholder/hint/button)."
      placeholder: "e.g. FirstName LastName"
    validations:
      required: true

  - type: input
    id: desired
    attributes:
      label: What should it say instead?
      placeholder: "e.g. FirstName LastName"
    validations:
      required: true

  - type: checkboxes
    id: constraints
    attributes:
      label: Constraints
      description: "Optional, but helps keep changes small."
      options:
        - label: Wording/UI text only (no behavior changes)
        - label: No changes to report output formatting
        - label: No changes outside this page/section

  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      description: Links/screenshots, or other context.
    validations:
      required: false
